---
- hosts: localhost
  become: true
  become_user: root

  tasks:
  - name: Start docker
    service: name=docker state=started

  - name: create docker image using war file
    command: docker build -t kushproject:CICD .
    args:
      chdir: /opt/CICD14OCT

  - name: create tag to image
    command: docker tag kushproject:CICD edu123/kushproject:CICD

  - name: loginto docker
    command: docker login --username edu123 --password Edureka@123

  - name: push image on to dockerhub
    command: docker push edu123/kushproject:CICD

  - name: remove docker images form ansible server
    command: docker rmi kushproject:CICD edu123/kushproject:CICD
    ignore_errors: yes
